import type { Property } from "@/types";

/**
 * Sample listing inventory.
 *
 * This module is the seam between the UI and wherever listings really live.
 * Swap it for a CMS query or the developer/DLD feed inside
 * `src/lib/repositories/properties.ts` — nothing else needs to change.
 */
export const properties: Property[] = [
  {
    slug: "como-residences-palm-jumeirah-sky-villa",
    name: "Como Residences — Sky Villa",
    headline: "A full-floor sky villa above the Palm",
    description:
      "A full-floor residence in Como Residences with a private pool on the terrace, uninterrupted sightlines along the Palm Jumeirah fronds and a private garage lift serving the apartment directly.",
    community: "Palm Jumeirah",
    communitySlug: "palm-jumeirah",
    city: "Dubai",
    intent: "buy",
    kind: "penthouse",
    price: { amount: 42000000, currency: "AED" },
    bedrooms: 4,
    bathrooms: 5,
    areaSqm: 726,
    developer: "Nakheel",
    handover: "Q4 2027",
    permitNumber: "DLD-71234567",
    features: [
      "Private terrace pool",
      "Direct garage lift access",
      "Panoramic sea views",
      "Fully fitted Italian kitchen",
    ],
    image: {
      src: "/images/properties/property-1.webp",
      alt: "Dark contemporary villa reflected in a long garden lap pool at dusk",
      width: 900,
      height: 900,
    },
    gallery: [
      { src: "/images/properties/property-1.webp", alt: "Dark contemporary villa reflected in a long garden lap pool at dusk", width: 900, height: 900 },
      { src: "/images/properties/property-3.webp", alt: "Bright living room with floor-to-ceiling sheer curtains and a curved sofa", width: 900, height: 900 },
      { src: "/images/properties/property-5.webp", alt: "Warmly lit living room with a low sofa, artwork and city views at night", width: 900, height: 900 },
    ],
    featured: true,
    publishedAt: "2026-06-02",
  },
  {
    slug: "signature-villa-palm-jumeirah-frond-k",
    name: "Signature Villa, Frond K",
    headline: "Beachfront living on a Palm Jumeirah frond",
    description:
      "A rebuilt Signature Villa on Frond K with 22 metres of private beach, a sculptural double-height entrance hall and a garden that steps straight down to the water.",
    community: "Palm Jumeirah",
    communitySlug: "palm-jumeirah",
    city: "Dubai",
    intent: "buy",
    kind: "villa",
    price: { amount: 68500000, currency: "AED" },
    bedrooms: 6,
    bathrooms: 7,
    areaSqm: 1114,
    developer: "Nakheel",
    permitNumber: "DLD-71234568",
    features: [
      "22 m private beach frontage",
      "Infinity pool and sunken lounge",
      "Staff and driver quarters",
      "Smart-home automation",
    ],
    image: {
      src: "/images/properties/property-2.webp",
      alt: "Curved contemporary beachfront villa framed by mature palm trees",
      width: 900,
      height: 900,
    },
    gallery: [
      { src: "/images/properties/property-2.webp", alt: "Curved contemporary beachfront villa framed by mature palm trees", width: 900, height: 900 },
      { src: "/images/properties/property-5.webp", alt: "Warmly lit living room with a low sofa, artwork and city views at night", width: 900, height: 900 },
      { src: "/images/properties/property-7.webp", alt: "Panelled living room with a statement artwork above a linen sofa", width: 900, height: 900 },
    ],
    featured: true,
    publishedAt: "2026-05-21",
  },
  {
    slug: "bluewaters-bay-three-bedroom-residence",
    name: "Bluewaters Bay Residence",
    headline: "Light-filled three-bedroom with marina views",
    description:
      "A corner residence in Bluewaters Bay with full-height glazing on two elevations, a wraparound terrace and views across the marina towards Ain Dubai.",
    community: "Bluewaters Island",
    communitySlug: "bluewaters-island",
    city: "Dubai",
    intent: "buy",
    kind: "apartment",
    price: { amount: 9750000, currency: "AED" },
    bedrooms: 3,
    bathrooms: 4,
    areaSqm: 214,
    developer: "Meraas",
    handover: "Q2 2027",
    permitNumber: "DLD-71234569",
    features: [
      "Dual-aspect corner layout",
      "Wraparound terrace",
      "Residents' beach club",
      "Concierge and valet",
    ],
    image: {
      src: "/images/properties/property-3.webp",
      alt: "Bright living room with floor-to-ceiling sheer curtains and a curved sofa",
      width: 900,
      height: 900,
    },
    gallery: [
      { src: "/images/properties/property-3.webp", alt: "Bright living room with floor-to-ceiling sheer curtains and a curved sofa", width: 900, height: 900 },
      { src: "/images/properties/property-7.webp", alt: "Panelled living room with a statement artwork above a linen sofa", width: 900, height: 900 },
      { src: "/images/properties/property-1.webp", alt: "Dark contemporary villa reflected in a long garden lap pool at dusk", width: 900, height: 900 },
    ],
    featured: true,
    publishedAt: "2026-05-14",
  },
  {
    slug: "district-one-west-lagoon-mansion",
    name: "District One West Mansion",
    headline: "Timber-clad mansion on the crystal lagoon",
    description:
      "A architect-designed mansion on the lagoon edge of District One West, wrapped in vertical timber with a reflecting pool that runs the length of the entertaining wing.",
    community: "Mohammed Bin Rashid City",
    communitySlug: "mohammed-bin-rashid-city",
    city: "Dubai",
    intent: "buy",
    kind: "villa",
    price: { amount: 31900000, currency: "AED" },
    bedrooms: 5,
    bathrooms: 6,
    areaSqm: 892,
    developer: "Nakheel",
    handover: "Q1 2028",
    permitNumber: "DLD-71234570",
    features: [
      "Direct crystal lagoon frontage",
      "Reflecting pool and cabana",
      "Home cinema and gym",
      "Four-car garage",
    ],
    image: {
      src: "/images/properties/property-4.webp",
      alt: "Low timber-clad villa mirrored in a still reflecting pool",
      width: 900,
      height: 900,
    },
    gallery: [
      { src: "/images/properties/property-4.webp", alt: "Low timber-clad villa mirrored in a still reflecting pool", width: 900, height: 900 },
      { src: "/images/properties/property-1.webp", alt: "Dark contemporary villa reflected in a long garden lap pool at dusk", width: 900, height: 900 },
      { src: "/images/properties/property-6.webp", alt: "Night render of an illuminated residential tower on the Dubai waterfront", width: 900, height: 900 },
    ],
    featured: true,
    publishedAt: "2026-05-03",
  },
  {
    slug: "downtown-boulevard-penthouse-rental",
    name: "Downtown Boulevard Penthouse",
    headline: "Furnished penthouse on Mohammed Bin Rashid Boulevard",
    description:
      "A fully furnished penthouse on the Boulevard with a wrapping balcony facing the Burj Khalifa, available on a twelve-month furnished lease with utilities managed.",
    community: "Downtown Dubai",
    communitySlug: "downtown-dubai",
    city: "Dubai",
    intent: "rent",
    kind: "penthouse",
    price: { amount: 1150000, currency: "AED" },
    pricePeriod: "year",
    bedrooms: 3,
    bathrooms: 4,
    areaSqm: 298,
    permitNumber: "DLD-71234571",
    features: [
      "Burj Khalifa and fountain views",
      "Fully furnished and serviced",
      "Two parking bays",
      "Twelve-month lease",
    ],
    image: {
      src: "/images/properties/property-5.webp",
      alt: "Warmly lit living room with a low sofa, artwork and city views at night",
      width: 900,
      height: 900,
    },
    gallery: [
      { src: "/images/properties/property-5.webp", alt: "Warmly lit living room with a low sofa, artwork and city views at night", width: 900, height: 900 },
      { src: "/images/properties/property-7.webp", alt: "Panelled living room with a statement artwork above a linen sofa", width: 900, height: 900 },
      { src: "/images/properties/property-3.webp", alt: "Bright living room with floor-to-ceiling sheer curtains and a curved sofa", width: 900, height: 900 },
    ],
    publishedAt: "2026-04-28",
  },
  {
    slug: "vivid-residences-dubai-marina-off-plan",
    name: "Vivid Residences",
    headline: "Off-plan waterfront tower on Dubai Marina",
    description:
      "A new waterfront tower on the Marina promenade with a 60/40 payment plan, branded interiors and a sky deck on the fifty-second floor.",
    community: "Dubai Marina",
    communitySlug: "dubai-marina",
    city: "Dubai",
    intent: "off-plan",
    kind: "off-plan",
    price: { amount: 2450000, currency: "AED" },
    bedrooms: 2,
    bathrooms: 3,
    areaSqm: 132,
    handover: "Q3 2028",
    permitNumber: "DLD-71234572",
    features: [
      "60/40 payment plan",
      "Branded interior package",
      "Level 52 sky deck",
      "Marina promenade frontage",
    ],
    image: {
      src: "/images/properties/property-6.webp",
      alt: "Night render of an illuminated residential tower on the Dubai waterfront",
      width: 900,
      height: 900,
    },
    gallery: [
      { src: "/images/properties/property-6.webp", alt: "Night render of an illuminated residential tower on the Dubai waterfront", width: 900, height: 900 },
      { src: "/images/properties/property-8.webp", alt: "Aerial view of a waterfront residential community with towers and a beach", width: 900, height: 900 },
      { src: "/images/properties/property-4.webp", alt: "Low timber-clad villa mirrored in a still reflecting pool", width: 900, height: 900 },
    ],
    publishedAt: "2026-04-19",
  },
  {
    slug: "jumeirah-bay-island-townhouse",
    name: "Jumeirah Bay Island Townhouse",
    headline: "Gallery-quality townhouse on Jumeirah Bay",
    description:
      "A four-bedroom townhouse on Jumeirah Bay Island finished by a Milanese studio, with fluted wall panelling, a private lift and a rooftop terrace facing the skyline.",
    community: "Jumeirah Bay Island",
    communitySlug: "jumeirah-bay-island",
    city: "Dubai",
    intent: "buy",
    kind: "townhouse",
    price: { amount: 18400000, currency: "AED" },
    bedrooms: 4,
    bathrooms: 5,
    areaSqm: 386,
    permitNumber: "DLD-71234573",
    features: [
      "Private internal lift",
      "Rooftop entertaining terrace",
      "Bespoke Italian joinery",
      "Gated island community",
    ],
    image: {
      src: "/images/properties/property-7.webp",
      alt: "Panelled living room with a statement artwork above a linen sofa",
      width: 900,
      height: 900,
    },
    gallery: [
      { src: "/images/properties/property-7.webp", alt: "Panelled living room with a statement artwork above a linen sofa", width: 900, height: 900 },
      { src: "/images/properties/property-3.webp", alt: "Bright living room with floor-to-ceiling sheer curtains and a curved sofa", width: 900, height: 900 },
      { src: "/images/properties/property-5.webp", alt: "Warmly lit living room with a low sofa, artwork and city views at night", width: 900, height: 900 },
    ],
    publishedAt: "2026-04-08",
  },
  {
    slug: "emaar-beachfront-seafront-apartment",
    name: "Emaar Beachfront Seafront Apartment",
    headline: "Private-beach apartment on Emaar Beachfront",
    description:
      "A high-floor apartment on Emaar Beachfront with direct access to 1.5 km of private beach, an infinity deck over the marina and Palm Jumeirah views from every room.",
    community: "Emaar Beachfront",
    communitySlug: "emaar-beachfront",
    city: "Dubai",
    intent: "buy",
    kind: "waterfront",
    price: { amount: 7200000, currency: "AED" },
    bedrooms: 3,
    bathrooms: 4,
    areaSqm: 186,
    developer: "Emaar",
    handover: "Q4 2026",
    permitNumber: "DLD-71234574",
    features: [
      "1.5 km private beach access",
      "Infinity pool deck",
      "Palm Jumeirah skyline views",
      "Walk to Dubai Marina Mall",
    ],
    image: {
      src: "/images/properties/property-8.webp",
      alt: "Aerial view of a waterfront residential community with towers and a beach",
      width: 900,
      height: 900,
    },
    gallery: [
      { src: "/images/properties/property-8.webp", alt: "Aerial view of a waterfront residential community with towers and a beach", width: 900, height: 900 },
      { src: "/images/properties/property-6.webp", alt: "Night render of an illuminated residential tower on the Dubai waterfront", width: 900, height: 900 },
      { src: "/images/properties/property-2.webp", alt: "Curved contemporary beachfront villa framed by mature palm trees", width: 900, height: 900 },
    ],
    publishedAt: "2026-03-30",
  },
];

/**
 * Three more off-plan launches so the off-plan grid (node 981:2981) has the
 * two-by-two it is drawn with. Sample data like the rest of this file — the
 * artboard fills all four cards with the same placeholder listing. Photography
 * is reused from the listings above; swap it with the real launch imagery.
 */
const offPlanLaunches: Property[] = [
  {
    slug: "avarra-business-bay-off-plan",
    name: "Avarra by Palace",
    headline: "Palace-branded residences on the Business Bay canal",
    description:
      "Palace-branded apartments and duplexes on the Business Bay waterfront, with the hotel's service desk, spa and restaurants attached to the residential lobby.",
    community: "Business Bay",
    communitySlug: "business-bay",
    city: "Dubai",
    intent: "off-plan",
    kind: "apartment",
    price: { amount: 2700000, currency: "AED" },
    bedrooms: 2,
    bathrooms: 3,
    areaSqm: 138,
    developer: "Emaar",
    handover: "Q2 2029",
    permitNumber: "DLD-71811204",
    features: [
      "Palace-branded service",
      "Canal-front position",
      "Direct Downtown access",
      "60/40 payment plan",
    ],
    image: {
      src: "/images/properties/property-2.webp",
      alt: "Warm-lit villa behind mature palms at dusk",
      width: 900,
      height: 900,
    },
    publishedAt: "2026-08-20",
  },
  {
    slug: "the-oasis-lagoon-villas-off-plan",
    name: "The Oasis — Lagoon Villas",
    headline: "Water-facing villas in Emaar's newest masterplan",
    description:
      "Detached villas set around swimmable lagoons and parkland in The Oasis, Emaar's low-density masterplan on the western edge of the city.",
    community: "The Oasis",
    communitySlug: "the-oasis",
    city: "Dubai",
    intent: "off-plan",
    kind: "villa",
    price: { amount: 8900000, currency: "AED" },
    bedrooms: 5,
    bathrooms: 6,
    areaSqm: 604,
    developer: "Emaar",
    handover: "Q4 2029",
    permitNumber: "DLD-71811337",
    features: [
      "Swimmable lagoon frontage",
      "Low-density masterplan",
      "Private garden and pool",
      "80/20 payment plan",
    ],
    image: {
      src: "/images/properties/property-4.webp",
      alt: "Courtyard villa with arcaded walkways around a reflecting pool",
      width: 900,
      height: 900,
    },
    publishedAt: "2026-08-12",
  },
  {
    slug: "palm-jebel-ali-beach-villas-off-plan",
    name: "Palm Jebel Ali — Beach Villas",
    headline: "Beach-front plots on the new Palm",
    description:
      "Beach-front villas on the fronds of Palm Jebel Ali, each with private sand and a choice of two architectural families.",
    community: "Palm Jebel Ali",
    communitySlug: "palm-jebel-ali",
    city: "Dubai",
    intent: "off-plan",
    kind: "villa",
    price: { amount: 18500000, currency: "AED" },
    bedrooms: 6,
    bathrooms: 7,
    areaSqm: 892,
    developer: "Nakheel",
    handover: "Q1 2030",
    permitNumber: "DLD-71811492",
    features: [
      "Private beach frontage",
      "Two architectural families",
      "Frond position",
      "Post-handover payment plan",
    ],
    image: {
      src: "/images/properties/property-8.webp",
      alt: "Modern villa with floor-to-ceiling glazing opening onto a terrace",
      width: 900,
      height: 900,
    },
    publishedAt: "2026-07-30",
  },
];

properties.push(...offPlanLaunches);
